# Generated by Django 6.0 on 2026-02-11 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Descripción')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('category', models.CharField(choices=[('ALIMENTO', 'Alimento'), ('MEDICAMENTO', 'Medicamento'), ('SUELDOS', 'Sueldos'), ('TRANSPORTE', 'Transporte'), ('MANTENIMIENTO', 'Mantenimiento'), ('OTROS', 'Otros')], default='OTROS', max_length=20, verbose_name='Categoría')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
