# Generated by Django 6.0 on 2026-04-07 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expense_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('ALIMENTO', 'Alimento'), ('MEDICAMENTO', 'Medicamento'), ('SUELDOS', 'Sueldos'), ('TRANSPORTE', 'Transporte'), ('MANTENIMIENTO', 'Mantenimiento'), ('TARJETA_CREDITO', 'Tarjeta de Crédito'), ('OTROS', 'Otros')], default='OTROS', max_length=20, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('TARJETA_CREDITO', 'Tarjeta de Crédito')], default='EFECTIVO', max_length=15, verbose_name='Método de Pago'),
        ),
    ]
