# Generated by Django 6.0 on 2026-07-10 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_alter_expense_category_alter_expense_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('ALIMENTO', 'Alimento'), ('MEDICAMENTO', 'Medicamento'), ('SUELDOS', 'Sueldos'), ('TRANSPORTE', 'Transporte'), ('MANTENIMIENTO', 'Mantenimiento'), ('TARJETA_CREDITO', 'Tarjeta de Crédito'), ('COMPRA_HUEVO', 'Compra de Huevo a Proveedor'), ('OTROS', 'Otros')], default='OTROS', max_length=20, verbose_name='Categoría'),
        ),
    ]
