# Generated by Django 6.0 on 2025-12-23 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='movement_type',
            field=models.CharField(choices=[('PRODUCCION', 'Producción'), ('VENTA', 'Venta'), ('TRASPASO_ENTRADA', 'Traspaso (Entrada)'), ('TRASPASO_SALIDA', 'Traspaso (Salida)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
