# Generated by Django 6.0 on 2026-01-14 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_inventory_quantity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name': 'Inventario', 'verbose_name_plural': 'Inventarios'},
        ),
        migrations.AlterModelOptions(
            name='inventorymovement',
            options={'verbose_name': 'Movimiento de Inventario', 'verbose_name_plural': 'Movimientos de Inventario'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Ubicación', 'verbose_name_plural': 'Ubicaciones'},
        ),
        migrations.AlterField(
            model_name='inventory',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.location', verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.location', verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='merma',
            field=models.IntegerField(default=0, verbose_name='Merma'),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='movement_type',
            field=models.CharField(choices=[('PRODUCCION', 'Producción'), ('VENTA', 'Venta'), ('TRASPASO_ENTRADA', 'Traspaso (Entrada)'), ('TRASPASO_SALIDA', 'Traspaso (Salida)')], max_length=20, verbose_name='Tipo de Movimiento'),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='quantity',
            field=models.IntegerField(verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
    ]
