# Generated by Django 6.0 on 2026-02-11 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_inventory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymovement',
            name='movement_type',
            field=models.CharField(choices=[('PRODUCCION', 'Producción'), ('VENTA', 'Venta'), ('TRASPASO_ENTRADA', 'Traspaso (Entrada)'), ('TRASPASO_SALIDA', 'Traspaso (Salida)'), ('CORRECCION', 'Corrección de Inventario')], max_length=20, verbose_name='Tipo de Movimiento'),
        ),
    ]
