# Generated by Django 6.0 on 2026-02-11 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_alter_inventory_id_alter_inventorymovement_id_and_more"),
        ("inventory", "0004_alter_inventorymovement_movement_type"),
    ]

    operations = []
