# Generated by Django 6.0 on 2026-06-02 18:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_inventorymovement_movement_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymovement',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha'),
        ),
    ]
