# Generated by Django 6.0 on 2026-07-08 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_inventorymovement_date_editable'),
        ('sales', '0006_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymovement',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_movements', to='sales.sale', verbose_name='Venta'),
        ),
    ]
