# Generated by Django 5.1.3 on 2026-07-08 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_merge_20260211_0020"),
        ("inventory", "0006_inventorymovement_sale"),
    ]

    operations = []
