# Generated by Django 6.0 on 2026-07-08 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_inventorymovement_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del Producto')),
                ('category', models.CharField(choices=[('HUEVO', 'Huevo'), ('MIEL', 'Miel'), ('SALSA', 'Salsa de Tomate'), ('MERMELADA', 'Mermelada'), ('PAN', 'Pan de Masa Madre'), ('OTROS', 'Otros Productos')], default='HUEVO', max_length=20, verbose_name='Categoría')),
                ('unit_type', models.CharField(choices=[('KILO', 'Kilo'), ('PIEZA', 'Pieza'), ('CAJA', 'Caja'), ('PAQUETE', 'Paquete')], default='KILO', max_length=10, verbose_name='Unidad de Medida')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio de Costo (Proveedor)')),
                ('sale_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio de Venta Sugerido')),
                ('profit_split_owner_pct', models.DecimalField(decimal_places=2, default=50.0, max_digits=5, verbose_name='% Utilidad Propietario (Tío Paul)')),
                ('profit_split_partner_pct', models.DecimalField(decimal_places=2, default=50.0, max_digits=5, verbose_name='% Utilidad Socio/Inversionista')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del Proveedor')),
                ('contact_name', models.CharField(blank=True, max_length=255, verbose_name='Nombre de Contacto')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo Electrónico')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.AddField(
            model_name='inventory',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='Producto'),
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('location', 'product')},
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.supplier', verbose_name='Proveedor'),
        ),
    ]
