# Generated by Django 6.0 on 2026-07-08 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_merge_20260707_2058'),
        ('inventory', '0007_product_supplier_inventory_product_and_more'),
    ]

    operations = [
    ]
