# Generated by Django 6.0 on 2026-07-09 19:07

from django.db import migrations
from decimal import Decimal

def populate_coords(apps, schema_editor):
    Location = apps.get_model('inventory', 'Location')
    coords_map = {
        'San Manuel': (Decimal('19.018000'), Decimal('-98.190100')),
        'Zacatelco': (Decimal('19.172800'), Decimal('-98.239300')),
        'Zacatelco Huevo Blanco': (Decimal('19.172800'), Decimal('-98.239300')),
        'Lomas de Angelópolis': (Decimal('19.030500'), Decimal('-98.269900')),
        'Momoxpan': (Decimal('19.066400'), Decimal('-98.269200')),
    }
    for name, coords in coords_map.items():
        Location.objects.filter(name=name).update(latitude=coords[0], longitude=coords[1])

def reverse_coords(apps, schema_editor):
    Location = apps.get_model('inventory', 'Location')
    Location.objects.all().update(latitude=None, longitude=None)

class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_location_latitude_location_longitude'),
    ]

    operations = [
        migrations.RunPython(populate_coords, reverse_coords),
    ]
