# Generated by Django 6.0 on 2026-07-09 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_populate_location_coords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='profit_split_owner_pct',
        ),
        migrations.RemoveField(
            model_name='product',
            name='profit_split_partner_pct',
        ),
    ]
