# Generated by Django 6.0 on 2026-07-10 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_remove_product_profit_split_owner_pct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('HUEVO', 'Huevo')], default='HUEVO', max_length=20, verbose_name='Categoría'),
        ),
    ]
