# Generated by Django 6.0 on 2026-07-10 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit_type',
            field=models.CharField(choices=[('KILO', 'Kilo'), ('PIEZA', 'Pieza')], default='KILO', max_length=10, verbose_name='Unidad de Medida'),
        ),
    ]
