# Generated by Django 6.0 on 2026-07-10 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_alter_product_unit_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymovement',
            name='movement_type',
            field=models.CharField(choices=[('PRODUCCION', 'Producción'), ('COMPRA', 'Compra a Proveedor (Entrada)'), ('VENTA', 'Venta'), ('TRASPASO_ENTRADA', 'Traspaso (Entrada)'), ('TRASPASO_SALIDA', 'Traspaso (Salida)'), ('CORRECCION', 'Corrección de Inventario')], max_length=20, verbose_name='Tipo de Movimiento'),
        ),
    ]
