# Generated by Django 5.1.3 on 2026-01-14 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_alter_customer_options_alter_customer_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
