# Generated by Django 6.0 on 2026-07-08 02:03

from django.db import migrations

def split_customer_names(apps, schema_editor):
    Customer = apps.get_model('customers', 'Customer')
    for customer in Customer.objects.all():
        full_name = customer.first_name.strip()
        if ' ' in full_name:
            parts = full_name.split(' ', 1)
            customer.first_name = parts[0]
            customer.last_name = parts[1]
            customer.save()

class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_rename_name_customer_first_name_customer_last_name_and_more'),
    ]

    operations = [
        migrations.RunPython(split_customer_names),
    ]

