# Generated by Django 6.0 on 2026-07-08 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_auto_20260707_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fraccionamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Fraccionamiento',
                'verbose_name_plural': 'Fraccionamientos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Zona',
                'verbose_name_plural': 'Zonas',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='fraccionamiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.fraccionamiento', verbose_name='Fraccionamiento'),
        ),
        migrations.AddField(
            model_name='customer',
            name='zona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.zona', verbose_name='Zona'),
        ),
    ]
