# Generated by Django 6.0 on 2026-07-08 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_fraccionamiento_zona_customer_fraccionamiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitud'),
        ),
        migrations.AddField(
            model_name='customer',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitud'),
        ),
    ]
