# Generated by Django 5.1.3 on 2026-07-08 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0003_alter_customer_id"),
        ("customers", "0005_fraccionamiento_zona_customer_fraccionamiento_and_more"),
    ]

    operations = []
