# Generated by Django 6.0 on 2026-07-08 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_customer_latitude_customer_longitude'),
        ('customers', '0006_merge_20260707_2058'),
    ]

    operations = [
    ]
