# Generated by Django 6.0 on 2026-07-13 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_alter_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='seller',
        ),
    ]
