# Generated by Django 6.0 on 2026-01-14 02:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_options_alter_customer_address_and_more'),
        ('inventory', '0003_alter_inventory_options_and_more'),
        ('sales', '0003_sale_location_sale_unit_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'verbose_name': 'Venta', 'verbose_name_plural': 'Ventas'},
        ),
        migrations.AddField(
            model_name='sale',
            name='is_paid',
            field=models.BooleanField(default=True, verbose_name='Pagado'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Pagado'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='day',
            field=models.DateField(verbose_name='Día'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='day_of_week',
            field=models.CharField(blank=True, max_length=10, verbose_name='Día de la semana'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.location', verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_date',
            field=models.DateField(verbose_name='Fecha de Pago'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia')], max_length=15, verbose_name='Método de Pago'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='quantity_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cantidad (Kg)'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='quantity_piece',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cantidad (Piezas)'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_type',
            field=models.CharField(choices=[('KILO', 'Kilo'), ('PIEZA', 'Pieza')], max_length=5, verbose_name='Tipo de Venta'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Vendedor'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Unitario'),
        ),
    ]
