# Generated by Django 6.0 on 2026-03-19 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_options_alter_customer_address_and_more'),
        ('inventory', '0004_alter_inventorymovement_movement_type'),
        ('sales', '0004_alter_sale_options_sale_is_paid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('sale_type', models.CharField(choices=[('KILO', 'Kilo'), ('PIEZA', 'Pieza')], max_length=5, verbose_name='Tipo de Venta')),
                ('quantity_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cantidad (Kg)')),
                ('quantity_piece', models.IntegerField(blank=True, null=True, verbose_name='Cantidad (Piezas)')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Unitario')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=15, verbose_name='Estado')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer', verbose_name='Cliente')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.location', verbose_name='Ubicación')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-created_at'],
            },
        ),
    ]
