# Generated by Django 5.1.3 on 2026-01-14 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0004_alter_sale_options_sale_is_paid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
