# Generated by Django 6.0 on 2026-03-19 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia')], default='EFECTIVO', max_length=15, verbose_name='Método de Pago'),
        ),
    ]
