# Generated by Django 6.0 on 2026-03-19 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0005_alter_sale_id"),
        ("sales", "0006_order_payment_method"),
    ]

    operations = []
