# Generated by Django 6.0 on 2026-07-08 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_customer_latitude_customer_longitude'),
        ('inventory', '0007_product_supplier_inventory_product_and_more'),
        ('sales', '0006_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.product', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='sale',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio de Costo'),
        ),
        migrations.AddField(
            model_name='sale',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.product', verbose_name='Producto'),
        ),
        migrations.CreateModel(
            name='RecurringOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad')),
                ('frequency', models.CharField(choices=[('SEMANAL', 'Semanal'), ('QUINCENAL', 'Quincenal'), ('MENSUAL', 'Mensual')], default='SEMANAL', max_length=15, verbose_name='Frecuencia')),
                ('day_of_week', models.IntegerField(blank=True, choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], null=True, verbose_name='Día de la Semana')),
                ('day_of_month', models.IntegerField(blank=True, null=True, verbose_name='Día del Mes')),
                ('last_generated_date', models.DateField(blank=True, null=True, verbose_name='Última Fecha Generada')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer', verbose_name='Cliente')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Pedido Recurrente',
                'verbose_name_plural': 'Pedidos Recurrentes',
            },
        ),
    ]
