# Generated by Django 6.0 on 2026-07-08 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_merge_0005_alter_sale_id_0006_order_payment_method'),
        ('sales', '0007_order_product_sale_cost_price_sale_product_and_more'),
    ]

    operations = [
    ]
