# Generated by Django 6.0 on 2026-07-08 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_merge_20260707_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Reparto'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
