# Generated by Django 6.0 on 2026-07-09 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_order_delivery_date_alter_sale_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringorder',
            name='day_of_week',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Días de la Semana'),
        ),
    ]
