# Generated by Django 6.0 on 2026-07-09 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_remove_product_profit_split_owner_pct_and_more'),
        ('sales', '0010_alter_recurringorder_day_of_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringorder',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.location', verbose_name='Ubicación de Origen'),
        ),
    ]
