# Generated by Django 6.0 on 2026-07-10 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_recurringorder_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurringorder',
            name='quantity',
        ),
        migrations.AddField(
            model_name='recurringorder',
            name='payment_method',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia')], default='EFECTIVO', max_length=15, verbose_name='Método de Pago'),
        ),
        migrations.AddField(
            model_name='recurringorder',
            name='quantity_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cantidad (Kg)'),
        ),
        migrations.AddField(
            model_name='recurringorder',
            name='quantity_piece',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cantidad (Piezas)'),
        ),
        migrations.AddField(
            model_name='recurringorder',
            name='sale_type',
            field=models.CharField(choices=[('KILO', 'Kilo'), ('PIEZA', 'Pieza')], default='PIEZA', max_length=5, verbose_name='Tipo de Venta'),
        ),
        migrations.AddField(
            model_name='recurringorder',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total'),
        ),
        migrations.AddField(
            model_name='recurringorder',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio Unitario'),
        ),
    ]
